path="/usr/local/bin/script.sh"
echo "${path##*/}"
echo "${path%%/*}"
echo "${path#/*/}"
echo "${path%.*}"
echo "${#path}"
empty=""
echo "a${empty:-def}b"
echo "a${empty:+set}b"
echo "a${missing:=default}b"
echo "missing=$missing"
echo "${path:5}"
echo "${path:0:4}"
